FROM httpd:latest

WORKDIR /Users/shubham gupta/Desktop

ARG DEBIAN_FRONTEND=noninteractive

ENV TZ=Indian                                                                                                                                                                                                                                                                                                    

RUN apt-get -y update
RUN apt-get install -y apache2

EXPOSE 80

COPY in.html /var/www/html/in.html

CMD [ "/usr/sbin/apache2ctl", "-D", "FOREGROUND" ]