# Derived from official mysql image (our base image)
FROM mysql 
ENV MYSQL_DATABASE User 
# All scripts in docker-entrypoint-initdb.d/ are automatically
# executed during container startup
COPY . /docker-entrypoint-initdb.d/